CREATE TABLE `sensor_data` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`json_message_ID` VARCHAR ( 30 ) NOT NULL,
	`processor_code` VARCHAR ( 50 ) NOT NULL DEFAULT '00001',
	`processor_shortname` VARCHAR ( 20 ) NOT NULL DEFAULT 'RaspberryPi 4',
	`processor_model` VARCHAR ( 255 ) NOT NULL DEFAULT 'modelA',
	`sensor_name` VARCHAR ( 20 ) NOT NULL,
	`capture_type` VARCHAR ( 30 ) NOT NULL DEFAULT 'AMBIENT_AIR',
	`data_capture_event` VARCHAR ( 30 ) NOT NULL DEFAULT 'xxxx_xxxxxxxx_xx_x',
	`capture_date_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	`event_index` SMALLINT NOT NULL DEFAULT '0',
	`sensate_name` VARCHAR ( 20 ) NOT NULL DEFAULT 'co2',
	`ppm` FLOAT ( 10, 2 ) NOT NULL,
	`celcius` FLOAT ( 10, 2 ) NOT NULL,
	`temperature` FLOAT ( 10, 2 ) NOT NULL,
	`humidity` FLOAT ( 10, 2 ) NOT NULL,
	`filtername` VARCHAR ( 50 ) NOT NULL DEFAULT '',
	`longitude` FLOAT ( 10, 4 ) NOT NULL,
	`latitude` FLOAT ( 10, 4 ) NOT NULL,
	`hs_model` VARCHAR ( 30 ) NOT NULL DEFAULT '',
	`hs_manufacturer` VARCHAR ( 30 ) NOT NULL DEFAULT '',
	`hs_description` VARCHAR ( 30 ) NOT NULL DEFAULT '',
	`fuel_name` VARCHAR ( 255 ) NOT NULL DEFAULT '',
	`hst_description` VARCHAR ( 30 ) NOT NULL DEFAULT '',
	`fu_filter_name` VARCHAR ( 50 ) NOT NULL DEFAULT '',
	`fu_filter_model` VARCHAR ( 10 ) NOT NULL DEFAULT '',
	`c_RFID` VARCHAR ( 100 ) NOT NULL DEFAULT '',
	`c_installed` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	`ct_description` VARCHAR ( 20 ) NOT NULL DEFAULT '',
	`status` VARCHAR ( 255 ) NOT NULL DEFAULT '',
	`ssma_timestamp` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY ( `ID` ) 
) ENGINE = INNODB AUTO_INCREMENT = 4965 DEFAULT CHARSET = utf8mb3;